# 插件基础信息
name: XLRGuiCrop
version: 1.0.0
main: xlingran.com.Shan
api-version: "26.2"
author: xlingran
description: Multi-Functional Virtual Crops Plugin
softdepend: [Vault]

# 命令
commands:
  xlr:
    description: XLRGuiCrop 主命令
    usage: /xlr farm | /xlr crop [create|farm|gui]
    aliases: []

# 权限
permissions:
  xlr.farm:
    description: 打开农田 GUI
    default: true
  xlr.crop:
    description: 打开农作物仓库 GUI
    default: true
  xlr.crop.create:
    description: 创建农田
    default: true
  xlr.admin:
    description: 骨粉页数解锁等管理指令
    default: op
