name: Auto Build Spigot
on:
  workflow_dispatch:

jobs:
  build-spigot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4

      # 配置Java稳定环境，移除了会报错的maven缓存配置
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # 下载Spigot官方原版BuildTools编译工具
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      # 编译版本
      - name: Compile Spigot Core
        run: java -jar BuildTools.jar --rev 1.26.2

      # 上传编译完成的纯净jar包
      - name: Upload Spigot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spigot
          path: '**/spigot-*.jar'
